routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts', 'ContactController');
Route::get('/search', 'ContactControlleur@search');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use DB;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $contacts = DB::table('contacts')->get();
        return view('contacts.index', ['contacts'=> $contacts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $inputs = $request->except('_token');

        $contact = new Contact();

        $contact->firstname = $request->input('firstname');
        $contact->lastname = $request->input('lastname');
        $contact->number = $request->input('number');
        $contact->email = $request->input('email');
        $contact->save();

        return redirect('contacts');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $contacts = Contact::find($id);
        return view('contacts.edit', ['contacts' => $contacts]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $inputs = $request->except('_token','_method');
        $contact = Contact::find($id);
        foreach($inputs as $key => $value){
            $contact->$key = $value;
        }
        $contact->save();

        return redirect('contacts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $contact = Contact::find($id);
        $contact->delete();

        return redirect('contacts');
    }
    public function search(Request $request)
    {
        $search = $request->get('search');
        $contacts = DB::table('contacts')->where('firstname', 'like', '%'.$search.'%');
        $contacts = DB::table('contacts')->where('lastname', 'like', '%'.$search.'%');
    return view('contacts.index', ['contacts'=>$contacts]);

    }
}

    

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contacts/create.blade.php
@extends('layouts.template')

@section('title', 'Créer Contact')

@section('content')

<form class="ml-3 mr-3" method="POST" action="{{route('contacts.store')}}">
@csrf
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="firstname">Firstname</label>
      <input type="text" name ="firstname" class="form-control" id="firstname">
    </div>
    
    <div class="form-group col-md-6">
      <label for="lastname">LastName</label>
      <input type="text" name="lastname" class="form-control" id="lastname">
    </div>
  </div>

  <div class="form-group">
    <label for="tel">Number</label>
    <input type="tel" name="number" class="form-control" id="number">
  </div>

  <div class="form-group">
    <label for="email">email</label>
    <input type="email" name="email" class="form-control" id="email"></input>
  </div>
  <button type="submit" class="btn btn-primary" style="margin-left:50%;">créer</button>
</form>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.template')

@section('title', 'Modifier Contact')

@section('content')

<form class="ml-3 mr-3" method="POST" action="{{route('contacts.update', ['contact' => $contacts->id])}}">
@method('PUT')
@csrf
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="firstname">Firstname</label>
      <input type="text" name ="firstname" class="form-control" id="firstname"  value="{{$contacts->firstname}}">
    </div>
    
    <div class="form-group col-md-6">
      <label for="lastname">LastName</label>
      <input type="text" name="lastname" class="form-control" id="lastname" value="{{$contacts->lastname}}">
    </div>
  </div>

  <div class="form-group">
    <label for="tel">Number</label>
    <input type="tel" name="number" class="form-control" id="number" value="{{$contacts->number}}">
  </div>

  <div class="form-group">
    <label for="email">email</label>
    <input type="email" name="email" class="form-control" id="email" value="{{$contacts->email}}"></input>
  </div>
  <button type="submit" class="btn btn-primary" style="margin-left:50%;">Mettre à jour</button>
</form>
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.template')

@section('title', 'Mes Contacts')

@section('content')
<div class="container mt-4">
  <div class="row" style="margin-right:70px">
    <div class="col py-4 px-lg-5 border bg-light text-center">Prénom</div>
    <div class="col py-3 px-lg-5 border bg-light text-center py-4">Nom</div>
    <div class="col py-3 px-lg-5 border bg-light text-center py-4">Téléhpone</div>
    <div class="col py-3 px-lg-5 border bg-light text-center py-4">Email</div>
  </div>
</div>
@foreach($contacts as $contact)

<div class="container mt-4">
        <div class="row  mb-2">
            <div class="col py-4 px-lg-5 border bg-light text-center">{{$contact->firstname}}</div>
            <div class="col py-3 px-lg-5 border bg-light text-center py-4">{{$contact->lastname}}</div>
            <div class="col py-3 px-lg-5 border bg-light text-center py-4">{{$contact->number}}</div>
            <div class="col py-3 px-lg-5 border bg-light text-center py-4">{{$contact->email}}</div>
          <div class="row d-flex ml-2" style="height: 40px; margin-top:25px;">
            <a class="btn btn-primary" href="{{route('contacts.edit', ['contact' => $contact->id])}}" role="button">
              <i class="fas fa-pen"></i>
            </a>
          </div>
          <form method="POST" action="{{route('contacts.destroy', ['contact' => $contact->id])}}">
            @method('DELETE')
            @csrf
            <div class="row  ml-4" style="height: 40px; margin-top:25px;">
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-trash"></i>
              </button>
            </div>
          </form>
        </div>
    </div>
@endforeach
<div class="row">
      <div class="mx-auto">
        <a class="btn btn-primary" href="{{route('contacts.create', ['contact' => $contact->id])}}" role="button">
          <i class="fas fa-plus-circle"></i>
        </a>
      <div>
    </div>
    

@endsection

resources/views/contacts/search.blade.php
@extends('layouts.template')

@section('title', 'Rechercher Contact')

@section('content')

<form class="ml-3 mr-3" method="POST" action="{{route('contacts.search', ['contact' => $contacts->id])}}">
@method('PUT')
@csrf
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="firstname">Firstname</label>
      <input type="text" name ="firstname" class="form-control" id="firstname"  value="{{$contacts->firstname}}">
    </div>
    
    <div class="form-group col-md-6">
      <label for="lastname">LastName</label>
      <input type="text" name="lastname" class="form-control" id="lastname" value="{{$contacts->lastname}}">
    </div>
  </div>
  <button type="submit" class="btn btn-primary" style="margin-left:50%;">Mettre à jour</button>
</form>

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous">     
    
    <title>@yield('title')</title>
</head>
<body>
<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand">TP - Contacts</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
     <a class="nav-item nav-link {{ Request::is('lists') ? 'active' : '' }}" href="contacts">Liste de contacts</a>
    </div>
  </div>
</nav>
</header>
</body>
<main>
     @yield('content')
</main>
</html>